### ISSUE TITLE
Clarification and questions

### ISSUE THREAD

**Issue by cnk113** [wenweixiong/MARVEL#1]
Hello,

I read your preprint and looked at the walkthrough which looks very thorough. I was wondering how the SJ/splicing is integrated from different single cell experiments and samples? Is there some sort of harmonization of the SJs? Also is the initial normalization step necessary for the gene counts? Most single cell normalization is done after QC filtering etc. It would be nice if that would be optional.

Thanks,
Chang

**Comment by wenweixiong** [comment]
Hi Chang,

Thank you for reaching out.

There will be no need to perform any harmonisation (i.e., batch correction etc) on the splice junction (SJ) counts. This is because, in plate-based methods, the percent spliced-in (PSI) value of a given alternative exon in a given cell represents the % of SJ reads supporting the alternative exon relative to the % of SJ reads supporting or skipping the alternative exon. In droplet-based methods, the PSI value of a given SJ in a given cell population represents the total number of SJ reads over the total number of reads mapping to the corresponding gene. Therefore, because the PSI values are percentages, they will be quite robust against experimental/batch effects.

Gene normalisation would need to be performed by the users prior to MARVEL. In plate-based method, MARVEL will only assist in log2-transformation of the user-provided normalised expression values (please see "Gene expression matrix" and "Transform expression values" sections of the plate-based tutorial). You may skip this step if you provided log2-transformed values. Similarly, for droplet-based method, users would need to provide the normalised expression values to MARVEL (please see "Normalised gene expression" section of the droplet-based tutorial). Log2-transformation will be performed by MARVEL prior to differential gene expression analysis or expression visualisation using _CompareValues.Genes.10x_ and _PlotValues.PCA.Gene.10x_ functions, respectively. To switch off log2-transformation, simply specify _log2.transform=FALSE_.

Hope this helps!

Sean

**Comment by wenweixiong** [comment]
If there is anything else please don't hesitate to reach out.

**Comment by wenweixiong** [comment]
If you have any other questions please don't hesitate to reach out.

**Comment by marcorainbow** [comment]
Hello, 

Thank you for developing the MARVEL package. I am following the droplet-based tutorial (https://wenweixiong.github.io/MARVEL_Droplet.html) and preprocessing some 10x Genomics reads. 

After performing the cellranger and STARsolo, I am not too sure on how to collate and combine the STARsolo count files for the downstream analysis. It would be nice if you could share some example codes for collating the count matrices correctly. 

Thanks a lot!

**Comment by wenweixiong** [comment]
Hi,

Example scripts and data to tabulate STARsolo splice junctions on https://github.com/wimm-hscb-lab-published/Wen_NucleicAcidsRes_2023


  *   script: scripts/scripts_02_prepare_marvel_input/script_01_2_prepare_input_raw_splice_junction_counts.R
  *   data: data/

Note that if there are too many splice junctions (i.e., file sizes are huge), you may want to filter in splice junctions (rows) expressed in, for example 1% of cells (columns), prior to tabulating the junctions across all samples/libraries.

Sean
________________________________
