### ISSUE TITLE
Can I use the MARVEL Droplet tutorial  to analyze plate-based data?

### ISSUE THREAD

**Issue by RongDing-NMU** [wenweixiong/MARVEL#12]
Hello,

Thanks for this useful package! I'm working on single cell splicing analysis. I noticed that the data preprocessing is different for droplet-based and plate-based libraries. Droplet-based data was processed using STARsolo, but plate-based data was processed using STAR + rMATs + Bedtools + RSEM. Since STARsolo can also analyze plate-based data, can I use the MARVEL Droplet tutorial (https://wenweixiong.github.io/MARVEL_Droplet.html) to analyze plate-based data?

Thanks.

**Comment by wenweixiong** [comment]
The insights provided by plate-based data is very different from droplet-based data, e.g., for plate-based pipeline/tutorial we will be able to perform exon-level splicing analysis, modality analysis, PCA, and nonsense-mediated decay prediction (NMD). These features are available for plate-, but not for droplet-based data simply because plate-based data typically has higher coverage.

In short, I strongly recommend plate-based tutorial for plate-based data.
