### ISSUE TITLE
Computing intron counts with script_03 takes ages

### ISSUE THREAD

**Issue by TdzBAS** [wenweixiong/MARVEL#21]
Hi Sean,

thanks again for your nice tool! It worked out pretty well, since last time. But now I am encountering some heavy efficiency issues for my large dataset.
I want to compute the intron counts with your script_03. I am using SGE and for one sample it takes hours to calculate it. In total I have 2000 samples. So the computation would take months..
Do you know how to speed things up?

This is the script I use:
[script3.txt](https://github.com/wenweixiong/MARVEL/files/12269722/script3.txt)

and one sample file:
[sample1.zip](https://github.com/wenweixiong/MARVEL/files/12269725/sample1.zip)

Glad for every help!
Thanks Sean!

Best,
Tolga

**Comment by wenweixiong** [comment]
Hi Tolga,

Admittedly this step is time-consuming. I typically run this step on my scientific computing platform (SCP). In this case, I submit one job for each cell via Slurm Workload Manager (v20.02.0) on CentOS Linux 7 (Core). Therefore all cells get processed in parallel and it typically takes ~24 hours to complete.

Do you have access to a SCP?

Sean

**Comment by TdzBAS** [comment]
Hi Sean,

thanks for your reply!

I have access to SGE, and can submit arrayjobs. But unfortunately only one job gets processed at a time. Which is the cause for the massive runtimes. For now I am a bit stucked in how to handle the runtime, so that I can get the results in the next two weeks.

Best
Tolga

**Comment by wenweixiong** [comment]
Hi Tolga,

I have written some scripts to tabulate and compute the intron counts "more efficiently".

The idea is that instead of processing one cell at a time, we first tabulate the per-base counts across all samples into a sparse matrix. Example scripts (script_01_create_example_file.txt), example input (sample1_1.txt, sample1_2.txt), and example output (example_input_sparse.rdata) on Google Drive (link expires this Sunday: https://drive.google.com/file/d/1OMf5C4NjKAE7Ut2e_B65D7BsbWXpJW0R/view?usp=sharing).

We then compute the intron counts for each intron by summing up the per-base counts using script_02_tabulate_intron_counts.txt. This should return the final intron count matrix ready to be used by MARVEL as per "Intron count matrix" of the tutorial.

The process will still take time, ~72 hours or more, but it circumvents the need to process one cell at a time.

Sean
________________________________

**Comment by wenweixiong** [comment]
Hi Tolga,

I have written some scripts to tabulate and compute the intron counts "more efficiently".

The idea is that instead of processing one cell at a time, we first tabulate the per-base counts across all samples into a sparse matrix. Example scripts (script_01_create_example_file.txt) and example input (sample1_1.txt, sample1_2.txt, Google Drive link )

[script_01_create_example_file.txt](https://github.com/wenweixiong/MARVEL/files/12421962/script_01_create_example_file.txt)

[sample1_1.txt.zip](https://github.com/wenweixiong/MARVEL/files/12421969/sample1_1.txt.zip)
[sample1_2.txt.zip](https://github.com/wenweixiong/MARVEL/files/12421974/sample1_2.txt.zip)

We then compute the intron counts for each intron by summing up the per-base counts using script_02_tabulate_intron_counts.txt. This should return the final intron count matrix ready to be used by MARVEL as per "Intron count matrix" of the tutorial.

[script_02_tabulate_intron_counts.txt](https://github.com/wenweixiong/MARVEL/files/12421976/script_02_tabulate_intron_counts.txt)

The process will still take time, but it circumvents the need to process one cell at a time.

Sean

**Comment by TdzBAS** [comment]
Hi Sean,

Big thanks for your help!
I will try it out tomorrow and will let you know how it went!

Best,

Tolga

Sean Wen ***@***.***> schrieb am Mi. 23. Aug. 2023 um 19:53:

**Comment by TdzBAS** [comment]
Hi Sean,

just a quick questions about the usage of script1.
Is it correct that I must adapt the files list like this, when I have 400
samples, where the first 200 samples belongs to cellgroup a and the last
200 samples belongs to cellgroup b:
files <- c("sample1.txt", "sample2.txt", .., "sample399.txt",
"sample400.txt")
?

thanks!
Best,
Tolga

Am Mi., 23. Aug. 2023 um 19:58 Uhr schrieb Tolga ***@***.***>:

**Comment by wenweixiong** [comment]
Hi Tolga,

The order of the samples/files shouldn't matter at this stage.

Sean
