### ISSUE TITLE
APA shortening and lengthening of 3'UTR for droplet-based data

### ISSUE THREAD

**Issue by Xiyuan0315** [wenweixiong/MARVEL#33]
Hi, thanks for providing this useful tool.
I noticed the way to quantify PSI for droplet-based data is SJ_count/Gene_count, and detailed information, like types of AS is not available. Is there any possibility to understand APA shortening and lengthening of 3'UTR based on output from SJ count from Starsolo using Marvel?

**Comment by wenweixiong** [comment]
Hi, droplet-based splicing analysis is restricted to splice junctions, therefore exon level splicing events such as skipped exons, mutually exclusively exons, retained introns, alternative 5' and 3' splice sites, or alternative first and last exons are not analysed. This is due to coverage bias towards the 3' or 5' end or non-uniform coverage across the isoforms. Unfortunately, APA or 3'-UTR length analyses are not supported by MARVEL.
