### ISSUE TITLE
Error in wiggleplotr::plotTranscripts

### ISSUE THREAD

**Issue by ziyanzhang1** [wenweixiong/MARVEL#5]
Hello,

I am following the droplet-based tutorial (https://wenweixiong.github.io/MARVEL_Droplet.html),I have encountered some problems.

when Locate SJ position:
marvel <- adhocGene.PlotSJPosition.10x(MarvelObject=marvel,
                                       coord.intron=coord.intron,
                                       rescale_introns=FALSE,  
                                       show.protein.coding.only=TRUE, 
                                       anno.label.size=1.5
                                      )
I received feedback :
Retrieving transcripts from GTF file...
12 transcripts identified
Error in wiggleplotr::plotTranscripts(exons = grange.exon.list, cdss = grange.cds.list,  : 
  unused arguments (anno.colors = anno.colors, anno.label.size = anno.label.size)

Maybe you can give me some advice.
Look forward to your reply！Thanks a lot!

**Comment by ziyanzhang1** [comment]
Thank you very much for your answer！ It worked.

But I still have a question: During the preprocessing process, can I skip cellranger and directly use STAR to process the fastq file? What are the consequences of doing this?

**Comment by ziyanzhang1** [comment]
Thank you very much for your answer！ It worked.

But I still have some questions: During the preprocessing process, can I skip cellranger and directly use STAR to process the fastq file? What are the consequences of doing this?

“STAR --genomeDir refdata-cellranger-GRCh38-3.0.0”

With the upgrade of STAR, the latest reference gene (Genome version: 20201) of cellranger is no longer applicable to STAR. Does the reference gene generated using STAR have an impact on subsequent analysis?

**Comment by wenweixiong** [comment]
You may run STAR on the FASTQ file (instead of BAM), but extra arguments are needed to specify the precise nucleotide position of the cell barcode and UMIs. These parameters varies with the library preparation chemistry, e.g., v2 vs v3 or 3' vs 5'. Please see "Barcode geometry" section of the STARsolo page:https://github.com/alexdobin/STAR/blob/master/docs/STARsolo.md

By running STAR on BAM, we simply need to specify the tags within the BAM that correspond to the cell barcode and UMI sequence (--soloInputSAMattrBarcodeSeq option). Please see "Preprocessing" section of MARVEL 10x Genomics tutorial (https://wenweixiong.github.io/MARVEL_Droplet.html).

You may whichever genome version suitable for STAR on your side...

**Comment by szhaoaf** [comment]
> Hi,
> 
> Please download the modified wiggleplotr package from here: http://datashare.molbiol.ox.ac.uk/public/wwen/wiggleplotr_1.18.0.tar.gz
> 
> And then install the package with: install.packages("wiggleplotr_1.18.0.tar.gz", repos=NULL, type="source")
> 
> This wiggleplotr package has been modified from the original CRAN version and should contain the arguments anno.colors and anno.label.size
> 
> Sean

Dear Sean,

Thanks for your fixing. However, the wiggleplotr_1.18.0.tar.gz link you provided did not exist any more.

Could you help provide the available link for downloading?

Bests,
Shizheng
